# Generated by Django 5.1.6 on 2025-04-08 09:54

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('emphasis_to_name', models.CharField(default='Event', max_length=10, verbose_name='Акцент к названию')),
                ('description', models.TextField(verbose_name='Описание')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('planned_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения')),
                ('registration_deadline', models.DateTimeField(verbose_name='Дата окончания регистрации')),
                ('event_number', models.CharField(blank=True, editable=False, max_length=8, unique=True)),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('show_on_main', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=core.utils.rename_uploaded_image, verbose_name='Фотография мероприятия')),
                ('hero_image', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.event')),
            ],
            options={
                'verbose_name': 'Фотография мероприятия',
                'verbose_name_plural': 'Фотографии мероприятий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Полное имя')),
                ('institution', models.CharField(blank=True, max_length=100, null=True, verbose_name='Учебное заведение')),
                ('tg', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('email', models.EmailField(max_length=50, verbose_name='Электронная почта')),
                ('project', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название проекта')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ваша роль в проекте')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на презентацию')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participants', to='events.event')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['-created_at'],
            },
        ),
    ]
