# Generated by Django 5.1.6 on 2025-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Электронная почта'),
        ),
    ]
