# Generated by Django 5.1.6 on 2025-04-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventphoto_event_alter_participant_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
    ]
