# Generated by Django 5.1.6 on 2025-04-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
