# Generated by Django 5.1.6 on 2025-04-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventtype_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='emphasis_to_name',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='description',
            field=models.TextField(default='Event description', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='emphasis_to_name',
            field=models.CharField(default='Event', max_length=10, verbose_name='Акцент к названию'),
        ),
    ]
