# Generated by Django 5.1.6 on 2025-04-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
    ]
