# Generated by Django 5.1.6 on 2025-04-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Название мероприятия', max_length=200, verbose_name='Название'),
        ),
    ]
