# Generated by Django 5.1.6 on 2025-04-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='value',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Значение'),
        ),
    ]
