# Generated by Django 5.1.6 on 2025-04-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='emphasis_to_name',
        ),
        migrations.AddField(
            model_name='event',
            name='emphasis_to_name',
            field=models.CharField(default='Event', max_length=10, verbose_name='Акцент к названию'),
        ),
    ]
