# Generated by Django 5.1.6 on 2025-04-24 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_eventtype_emphasis_to_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_title', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('step_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_timelines', to='events.eventtype', verbose_name='Тип мероприятия')),
            ],
            options={
                'verbose_name': 'Этап мероприятия',
                'verbose_name_plural': 'Этапы мероприятий',
                'ordering': ['-created_at'],
            },
        ),
    ]
