# Generated by Django 5.1.6 on 2025-04-28 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_eventtimeline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtimeline',
            options={'ordering': ['created_at'], 'verbose_name': 'Этап мероприятия', 'verbose_name_plural': 'Этапы мероприятий'},
        ),
        migrations.AddField(
            model_name='achievement',
            name='title_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Название на английском'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title_uz',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Название на узбекском'),
        ),
        migrations.AddField(
            model_name='event',
            name='emphasis_to_name_en',
            field=models.CharField(default='Event', max_length=10, verbose_name='Акцент к названию на английском'),
        ),
        migrations.AddField(
            model_name='event',
            name='emphasis_to_name_uz',
            field=models.CharField(default='Tadbir', max_length=10, verbose_name='Акцент к названию на узбекском'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Место проведения на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location_uz',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Место проведения на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='name_en',
            field=models.CharField(default='Event name', max_length=200, verbose_name='Название на английском'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_uz',
            field=models.CharField(default='Tadbir nomi', max_length=200, verbose_name='Название на узбекском'),
        ),
        migrations.AddField(
            model_name='eventtimeline',
            name='step_title_en',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Название этапа на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtimeline',
            name='step_title_uz',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Название этапа на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtype',
            name='description_en',
            field=models.TextField(blank=True, default='Event description', null=True, verbose_name='Описание на английском'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='description_uz',
            field=models.TextField(blank=True, default="Tadbir haqida ma'lumot", null=True, verbose_name='Описание на узбекском'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='name_en',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Название на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtype',
            name='name_uz',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Название на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventwinner',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание стартапа на английском'),
        ),
        migrations.AddField(
            model_name='eventwinner',
            name='description_uz',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание стартапа на узбекском'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Место проведения на русском'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='Название мероприятия', max_length=200, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='eventtimeline',
            name='step_title',
            field=models.CharField(max_length=200, verbose_name='Название этапа на русском'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=models.TextField(default='Event description', verbose_name='Описание на русском'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='eventwinner',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание стартапа на русском'),
        ),
    ]
