# Generated by Django 5.1.6 on 2025-05-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_eventtimeline_options_achievement_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='show_on_main',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
    ]
