# Generated by Django 5.1.6 on 2025-05-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_eventtype_show_on_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='link',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='project',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='role',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='tg',
        ),
        migrations.AddField(
            model_name='participant',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Согласны ли вы со съемкой вашей презентации, публикацией информации о вашем стартапе и делиться своими контактами с партнерами проекта и заинтересованными сторонами?'),
        ),
        migrations.AddField(
            model_name='participant',
            name='has_attracted_investment',
            field=models.BooleanField(default=False, verbose_name='Привлекали ли вы инвестиции в свой стартап?'),
        ),
        migrations.AddField(
            model_name='participant',
            name='has_entrepreneurship_experience',
            field=models.BooleanField(default=False, verbose_name='У вас был предпринимательский опыт ранее?'),
        ),
        migrations.AddField(
            model_name='participant',
            name='incubators_accelerators',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='В каких инкубаторах и/или акселераторах вы участвовали?'),
        ),
        migrations.AddField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(default=0, max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='position_in_startup',
            field=models.CharField(default=0, max_length=200, verbose_name='Ваша должность в стартапе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='presentation_link',
            field=models.URLField(default=0, max_length=500, verbose_name='Ссылка на презентацию стартапа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='startup_description',
            field=models.TextField(default=0, max_length=500, verbose_name='Краткая информация о стартапе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='startup_name',
            field=models.CharField(default=0, max_length=200, verbose_name='Название стартапа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='startup_sphere',
            field=models.CharField(choices=[('ecommerce', 'E-commerce'), ('edtech', 'EdTech'), ('fintech', 'FinTech'), ('medtech', 'MedTech'), ('agritech', 'AgriTech'), ('erp_crm', 'ERP/CRM'), ('entertainment', 'Entertainment'), ('other', 'Другое')], default=0, max_length=20, verbose_name='Сфера стартапа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='startup_sphere_other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Если другое, напишите'),
        ),
        migrations.AddField(
            model_name='participant',
            name='startup_status',
            field=models.CharField(choices=[('idea', 'Идея'), ('mvp', 'MVP'), ('traction', 'Есть продажи')], default=0, max_length=20, verbose_name='Статус стартапа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='tg_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(default=23, max_length=200, verbose_name='Полное имя'),
            preserve_default=False,
        ),
    ]
