# Generated by Django 5.1.6 on 2025-05-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_participant_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='presentation_link',
            field=models.CharField(max_length=500, verbose_name='Ссылка на презентацию стартапа'),
        ),
    ]
