# Generated by Django 5.1.6 on 2025-05-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_participant_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='startup_sphere',
            field=models.CharField(choices=[('ecommerce', 'E-commerce'), ('edtech', 'EdTech'), ('fintech', 'FinTech'), ('medtech', 'MedTech'), ('agritech', 'AgriTech'), ('erp_crm', 'ERP/CRM'), ('entertainment', 'Entertainment'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Сфера стартапа'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='startup_status',
            field=models.CharField(choices=[('idea', 'Идея'), ('mvp', 'MVP'), ('traction', 'Есть продажи')], default='idea', max_length=20, verbose_name='Статус стартапа'),
        ),
    ]
