# Generated by Django 5.1.6 on 2025-05-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_participant_startup_sphere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='consent',
            field=models.CharField(blank=True, choices=[('yes', 'Согласен'), ('no', 'Не согласен')], default='yes', max_length=3, null=True, verbose_name='Согласны ли вы со съемкой вашей презентации, публикацией информации о вашем стартапе и делиться своими контактами с партнерами проекта и заинтересованными сторонами?'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='has_attracted_investment',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], default='no', max_length=3, null=True, verbose_name='Привлекали ли вы инвестиции в свой стартап?'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='has_entrepreneurship_experience',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], default='no', max_length=3, null=True, verbose_name='У вас был предпринимательский опыт ранее?'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='position_in_startup',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ваша должность в стартапе'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='presentation_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на презентацию стартапа'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='startup_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткая информация о стартапе'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='startup_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название стартапа'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='startup_sphere',
            field=models.CharField(blank=True, choices=[('ecommerce', 'E-commerce'), ('edtech', 'EdTech'), ('fintech', 'FinTech'), ('medtech', 'MedTech'), ('agritech', 'AgriTech'), ('erp_crm', 'ERP/CRM'), ('entertainment', 'Entertainment'), ('other', 'Другое')], default='other', max_length=20, null=True, verbose_name='Сфера стартапа'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='startup_status',
            field=models.CharField(blank=True, choices=[('idea', 'Идея'), ('mvp', 'MVP'), ('traction', 'Есть продажи')], default='idea', max_length=20, null=True, verbose_name='Статус стартапа'),
        ),
    ]
