# Generated by Django 5.1.6 on 2025-05-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_participant_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='presentation_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на презентацию стартапа (убедитесь что открыт доступ к чтению)'),
        ),
    ]
