# Generated by Django 5.1.6 on 2025-04-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('website', models.CharField(blank=True, max_length=200, null=True, verbose_name='Сайт')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Почему хотите стать партнером?')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Логотипа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['-created_at'],
            },
        ),
    ]
