# Generated by Django 5.1.6 on 2025-04-24 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_achievement'),
        ('partners', '0002_partner_show_on_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='events.eventtype', verbose_name='Тип мероприятия'),
        ),
    ]
