# Generated by Django 5.1.6 on 2025-04-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_achievement_value'),
        ('partners', '0003_partner_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='event_type',
        ),
        migrations.AddField(
            model_name='partner',
            name='event_type',
            field=models.ManyToManyField(blank=True, related_name='partners', to='events.eventtype', verbose_name='Тип мероприятия'),
        ),
    ]
