# Generated by Django 5.1.6 on 2025-04-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_remove_partner_event_type_partner_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название на английском'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название на узбекском'),
        ),
    ]
