# Generated by Django 5.1.6 on 2025-04-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_partner_name_en_partner_name_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(blank=True, default='Партнер', help_text='Название на русском языке', max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_en',
            field=models.CharField(blank=True, help_text='Название на английском языке', max_length=200, null=True, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_uz',
            field=models.CharField(blank=True, help_text='Название на узбекском языке', max_length=200, null=True, verbose_name='Название на узбекском'),
        ),
    ]
