# Generated by Django 5.1.6 on 2025-04-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_alter_partner_name_alter_partner_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='registration_source',
            field=models.CharField(choices=[('website', 'Website'), ('admin', 'Admin')], default='website', max_length=50, verbose_name='Источник регистрации'),
        ),
    ]
