# Generated by Django 5.1.6 on 2025-04-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_partner_registration_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='registration_source',
            field=models.CharField(choices=[('website', 'Website'), ('admin', 'Admin')], default='admin', max_length=50, verbose_name='Источник регистрации'),
        ),
    ]
