# Generated by Django 5.1.6 on 2025-04-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_alter_partner_registration_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(blank=True, default='Партнер', help_text='Название на русском языке', max_length=200, null=True, verbose_name='Навзание'),
        ),
    ]
