# Generated by Django 5.1.6 on 2025-05-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_alter_partner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(blank=True, help_text='Название на русском языке', max_length=200, null=True, verbose_name='Название'),
        ),
    ]
