# Generated by Django 5.1.6 on 2025-05-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_alter_partner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='show_on_main',
            field=models.BooleanField(default=False, verbose_name='Показать на главной странице'),
        ),
    ]
