# Generated by Django 5.1.6 on 2025-04-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='show_on_website',
            field=models.BooleanField(default=False, verbose_name='Показать на сайте'),
        ),
    ]
