# Generated by Django 5.1.6 on 2025-04-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_mentor_show_on_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя и фамилия на английском'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='full_name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя и фамилия на узбекском'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='organization_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название организации на английском'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='organization_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название организации на узбекском'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='position_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность на английском'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='position_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность на узбекском'),
        ),
    ]
