# Generated by Django 5.1.6 on 2025-04-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_mentor_full_name_en_mentor_full_name_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='full_name',
            field=models.CharField(blank=True, default='Имя Фамилия', max_length=100, null=True, verbose_name='Имя и фамилия'),
        ),
    ]
