# Generated by Django 5.1.6 on 2025-04-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_alter_mentor_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='registration_source',
            field=models.CharField(choices=[('website', 'Website'), ('admin', 'Admin')], default='admin', max_length=50, verbose_name='Источник регистрации'),
        ),
    ]
